### ISSUE TITLE
 Query fails if using column from type TIMESTAMP WITH TIMEZONE in select clause

### ISSUE THREAD

**Issue by mguggi** [go-goracle/goracle#37]
When I executing the query `select originating_timestamp, message_text from v$diag_alert_ext` I receive the following error `assignment to entry in nil map`.

```
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 22 [running]:
testing.tRunner.func1(0xc4203a40f0)
	/home/mguggi/public/go-1.9.2/src/testing/testing.go:711 +0x2d2
panic(0xcf92c0, 0xe18a20)
	/home/mguggi/public/go-1.9.2/src/runtime/panic.go:491 +0x283
github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/goracle%2ev2.timeZoneFor(0x7fc76c1a0001, 0x7fc76c1aab68)
	/home/mguggi/go/src/github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/goracle.v2/drv.go:687 +0x3df
github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/goracle%2ev2.(*rows).Next(0xc42010db20, 0xc42010af00, 0x27, 0x27, 0x27, 0x27)
	/home/mguggi/go/src/github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/goracle.v2/rows.go:394 +0x2155
database/sql.(*Rows).nextLocked(0xc420354b80, 0xc420420000)
	/home/mguggi/public/go-1.9.2/src/database/sql/sql.go:2463 +0xc4
database/sql.(*Rows).Next.func1()
	/home/mguggi/public/go-1.9.2/src/database/sql/sql.go:2442 +0x3c
database/sql.withLock(0x12e1a00, 0xc420354bb0, 0xc420425a48)
	/home/mguggi/public/go-1.9.2/src/database/sql/sql.go:2867 +0x65
database/sql.(*Rows).Next(0xc420354b80, 0x1333c50)
	/home/mguggi/public/go-1.9.2/src/database/sql/sql.go:2441 +0x7a
github.com/mguggi/oraclebeat/module/oracle.Scan(0xc420354b80, 0x1333c50, 0xc420354b80, 0xc420425e40, 0x2, 0x2)
	/home/mguggi/go/src/github.com/mguggi/oraclebeat/module/oracle/oracle.go:82 +0xd27
github.com/mguggi/oraclebeat/module/oracle/alertlog.(*MetricSet).Fetch(0xc4201a8fa0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/mguggi/go/src/github.com/mguggi/oraclebeat/module/oracle/alertlog/alertlog.go:130 +0x5f6
github.com/mguggi/oraclebeat/module/oracle/alertlog.TestFetch(0xc4203a40f0)
	/home/mguggi/go/src/github.com/mguggi/oraclebeat/module/oracle/alertlog/alertlog_integration_test.go:18 +0xef
testing.tRunner(0xc4203a40f0, 0xdd0840)
	/home/mguggi/public/go-1.9.2/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/home/mguggi/public/go-1.9.2/src/testing/testing.go:789 +0x2de

Process finished with exit code 2
```

In the debug trace above you can see that the issue is in 

`github.com/mguggi/oraclebeat/module/oracle/vendor/gopkg.in/goracle%2ev2.timeZoneFor(0x7fc76c1a0001, 0x7fc76c1aab68)`

In my opinion this function has two problems. 

1. The timezones map will never initialized.
2. The timezonesMu.Unlock() call is outside from the if statement. 

I use the following environment: 

- oracle database 12.1.0.2 
- oracle client: 12.2.0.1 
- goracle 2.1.12

**Comment by mguggi** [comment]
I’m not really a golang expert but is it not possible to received the error below? 

`sync: Unlock of unlocked RWMutex`
