### ISSUE TITLE
Crash on call db.QueryContext(ctx, command)

### ISSUE THREAD

**Issue by nh-live** [go-goracle/goracle#84]
code:
       db,err := sql.Open(dbType,connStr)
	if err != nil {
		return nil,nil,errors.New("open database connection failed, " + err.Error())
	}

	db.SetMaxIdleConns(0)
	db.SetMaxOpenConns(1)

	defer db.Close()

	connCtx, connCancel := context.WithTimeout(context.Background(), time.Duration(connTimeout)*time.Second)
	defer connCancel()
	execCtx, execCancel := context.WithTimeout(context.Background(), time.Duration(execTimeout)*time.Second)
	defer execCancel()

	err = db.PingContext(connCtx)
	if err != nil {
		return nil,nil,errors.New("connect to database failed, " + err.Error())
	}

	rows, err := db.QueryContext(execCtx, command)
	if err != nil {
		return nil,nil,errors.New("execute sql failed, " + err.Error())
	}

	defer rows.Close()

crash trace:

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x7f4aec9bd0dc]

runtime stack:
runtime.throw(0xe70928, 0x2a)
        /alphawolf/code/linux/go/src/runtime/panic.go:619 +0x81
runtime.sigpanic()
        /alphawolf/code/linux/go/src/runtime/signal_unix.go:372 +0x28e

goroutine 15353 [syscall]:
runtime.cgocall(0xc34480, 0xc4213b3710, 0xc400000000)
        /alphawolf/code/linux/go/src/runtime/cgocall.go:128 +0x64 fp=0xc4213b36e0 sp=0xc4213b36a8 pc=0x40c2e4
gopkg.in/goracle%2ev2._Cfunc_dpiStmt_release(0x7f4ad0074b30, 0x7f4a00000000)
        _cgo_gotypes.go:2963 +0x49 fp=0xc4213b3710 sp=0xc4213b36e0 pc=0x912389
gopkg.in/goracle%2ev2.(*statement).close.func3(0x7f4ad0074b30, 0xc42211ae00)
        /alphawolf/code/go/src/gopkg.in/goracle.v2/stmt.go:167 +0x56 fp=0xc4213b3748 sp=0xc4213b3710 pc=0x937d46
gopkg.in/goracle%2ev2.(*statement).close(0xc420fb6500, 0x0, 0x0)
        /alphawolf/code/go/src/gopkg.in/goracle.v2/stmt.go:167 +0x254 fp=0xc4213b37b8 sp=0xc4213b3748 pc=0x924334
gopkg.in/goracle%2ev2.(*statement).QueryContext(0xc420fb6500, 0xf102e0, 0xc42243ff50, 0x173adb0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /alphawolf/code/go/src/gopkg.in/goracle.v2/stmt.go:448 +0x5ae fp=0xc4213b3978 sp=0xc4213b37b8 pc=0x92693e
database/sql.ctxDriverStmtQuery(0xf102e0, 0xc42243ff50, 0xf10ae0, 0xc420fb6500, 0x173adb0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /alphawolf/code/linux/go/src/database/sql/ctxutil.go:82 +0x214 fp=0xc4213b39f0 sp=0xc4213b3978 pc=0x812674
database/sql.rowsiFromStatement(0xf102e0, 0xc42243ff50, 0xf0f760, 0xc4209bc750, 0xc42093e500, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /alphawolf/code/linux/go/src/database/sql/sql.go:2450 +0x198 fp=0xc4213b3aa0 sp=0xc4213b39f0 pc=0x81dd28
database/sql.(*DB).queryDC(0xc421f4e3c0, 0xf102e0, 0xc42243ff50, 0x0, 0x0, 0xc421714700, 0xc4217631a0, 0xc42064a480, 0x210, 0x0, ...)
        /alphawolf/code/linux/go/src/database/sql/sql.go:1494 +0x25f fp=0xc4213b3c60 sp=0xc4213b3aa0 pc=0x81918f
database/sql.(*DB).query(0xc421f4e3c0, 0xf102e0, 0xc42243ff50, 0xc42064a480, 0x210, 0x0, 0x0, 0x0, 0xf10201, 0xc42168cba0, ...)
        /alphawolf/code/linux/go/src/database/sql/sql.go:1442 +0x13b fp=0xc4213b3cf0 sp=0xc4213b3c60 pc=0x818e9b
database/sql.(*DB).QueryContext(0xc421f4e3c0, 0xf102e0, 0xc42243ff50, 0xc42064a480, 0x210, 0x0, 0x0, 0x0, 0xc420bba0d0, 0xc420cbad10, ...)
        /alphawolf/code/linux/go/src/database/sql/sql.go:1419 +0xd2 fp=0xc4213b3d80 sp=0xc4213b3cf0 pc=0x818b02
alphawolf.com/eyeits/impls.(*Execute).Sql(0x173a9c0, 0xe4b0cf, 0x7, 0xc420bbd480, 0xc, 0xc420bbd490, 0x7, 0xc420bbd49e, 0x2, 0xc420bbd4b0, ...)

go version go1.10 linux/amd64

**Comment by nh-live** [comment]
use last GitHub master,the problem has been repaired,tks!!!
